# version of teh docker compose
version: "3.8"

services:
  client:
    build: 
      context: ./frontend
    container_name: clientapp_c
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  server:
    build: 
      context: ./backend
    container_name: overallapp_container
    ports:
      - "5000:5000"
    volumes: 
      - ./backend:/app
      - /app/node_modules
      - tntappbackend_volume:/app


volumes:
  tntappbackend_volume:

